insert into public.pets (slug, name, author, format, tags, image_path, source_url, status)
values
  ('super-saiyan-goku-combat', 'Super Saiyan Goku Combat', 'datpham', 'V2', array['animated', 'anime']::text[], '/pet-gallery/super-saiyan-goku-combat.webp', 'https://codex-pets.net/#/pets/super-saiyan-goku-combat', 'published'),
  ('frieren-maplestory-v2', 'frieren-maplestory-v2', 'side_inventory', 'V2', array['animated', 'anime', 'celeb', 'chaotic', 'cute']::text[], '/pet-gallery/frieren-maplestory-v2.webp', 'https://codex-pets.net/#/pets/frieren-maplestory-v2', 'published'),
  ('momonga', 'Momonga', 'side_inventory', 'V2', array['animated', 'anime', 'celeb', 'chaotic', 'cute', 'mascot']::text[], '/pet-gallery/momonga.webp', 'https://codex-pets.net/#/pets/momonga', 'published'),
  ('spinach', '菠菜', 'Greenhorn', 'V2', array['animated', 'cute', 'mascot', 'soft']::text[], '/pet-gallery/spinach.webp', 'https://codex-pets.net/#/pets/spinach', 'published'),
  ('nougat', '牛轧糖', 'Rover', 'V2', array['cute', 'anime']::text[], '/pet-gallery/nougat.webp', 'https://codex-pets.net/#/pets/nougat', 'published'),
  ('maguang', '码光', 'black', 'V2', array['animated', 'soft', 'pixel', 'cute']::text[], '/pet-gallery/maguang.webp', 'https://codex-pets.net/#/pets/maguang', 'published'),
  ('fangbao', '方宝', 'luo', 'V1', array['cute']::text[], '/pet-gallery/fangbao.webp', 'https://codex-pets.net/#/pets/fangbao', 'published'),
  ('mojo-apple', 'MOJO Apple', 'exile', 'V2', array['cute']::text[], '/pet-gallery/mojo-apple.webp', 'https://codex-pets.net/#/pets/mojo-apple', 'published'),
  ('silksong-hornet', '大黄蜂', 'Hornet', 'V2', array['game']::text[], '/pet-gallery/silksong-hornet.webp', 'https://codex-pets.net/#/pets/silksong-hornet', 'published'),
  ('purin-cat', 'Purin cat', 'Chierin', 'V2', array['animated', 'cute', 'pixel', 'mascot', 'soft']::text[], '/pet-gallery/purin-cat.webp', 'https://codex-pets.net/#/pets/purin-cat', 'published'),
  ('vegeta-z-feng', '贝吉塔', 'snailFeng', 'V2', '{}'::text[], '/pet-gallery/vegeta-z-feng.webp', 'https://codex-pets.net/#/pets/vegeta-z-feng', 'published'),
  ('aegis-sentinel', 'Aegis Sentinel', 'j3rbski', 'V2', array['animated', 'game']::text[], '/pet-gallery/aegis-sentinel.webp', 'https://codex-pets.net/#/pets/aegis-sentinel', 'published'),
  ('monthly-salary-cat-fix', '月薪喵', 'xiaoyyy', 'V2', array['cute', 'mascot', 'anime', 'minimal']::text[], '/pet-gallery/monthly-salary-cat-fix.webp', 'https://codex-pets.net/#/pets/monthly-salary-cat-fix', 'published'),
  ('mianmian', '棉棉 (Mianmian)', 'Feyy', 'V2', array['cute', 'soft']::text[], '/pet-gallery/mianmian.webp', 'https://codex-pets.net/#/pets/mianmian', 'published'),
  ('anna-yanami', '八奈见杏菜 Anna Yanami', 'magixixi', 'V1', array['animated', 'cute', 'anime', 'pixel']::text[], '/pet-gallery/anna-yanami.webp', 'https://codex-pets.net/#/pets/anna-yanami', 'published'),
  ('noah-lulu', '噜噜', 'noah', 'V2', array['animated', 'cute', 'mascot', 'soft']::text[], '/pet-gallery/noah-lulu.webp', 'https://codex-pets.net/#/pets/noah-lulu', 'published'),
  ('ash', 'Ash', 'zhero', 'V2', array['anime', 'cute', 'pixel', 'robot']::text[], '/pet-gallery/ash.webp', 'https://codex-pets.net/#/pets/ash', 'published'),
  ('iuno', 'Iuno', 'skyraker', 'V2', array['animated', 'anime', 'cute', 'game']::text[], '/pet-gallery/iuno.webp', 'https://codex-pets.net/#/pets/iuno', 'published'),
  ('xiao-hei-zi-v2', '小黑子-iKun', 'mayway', 'V2', array['celeb', 'cute', 'animated']::text[], '/pet-gallery/xiao-hei-zi-v2.webp', 'https://codex-pets.net/#/pets/xiao-hei-zi-v2', 'published'),
  ('xiaocheng', '小澄·薄荷助手', 'fichil', 'V2', array['animated', 'anime', 'cute']::text[], '/pet-gallery/xiaocheng.webp', 'https://codex-pets.net/#/pets/xiaocheng', 'published'),
  ('uta-anime', 'Uta Anime', 'whzhao', 'V2', '{}'::text[], '/pet-gallery/uta-anime.webp', 'https://codex-pets.net/#/pets/uta-anime', 'published'),
  ('uta-adult', 'Uta Adult', 'whzhao', 'V2', '{}'::text[], '/pet-gallery/uta-adult.webp', 'https://codex-pets.net/#/pets/uta-adult', 'published'),
  ('gutgeoni', '굳건이', '3ae3ae', 'V2', array['mascot', 'animated', 'cute']::text[], '/pet-gallery/gutgeoni.webp', 'https://codex-pets.net/#/pets/gutgeoni', 'published'),
  ('monthly-salary-cat-v2', '月薪喵', 'xiaoyyy', 'V2', array['anime', 'cute', 'mascot', 'minimal']::text[], '/pet-gallery/monthly-salary-cat-v2.webp', 'https://codex-pets.net/#/pets/monthly-salary-cat-v2', 'published'),
  ('kento-nanami', 'Kento Nanami', 'K4tNoeJ', 'V2', array['animated', 'anime']::text[], '/pet-gallery/kento-nanami.webp', 'https://codex-pets.net/#/pets/kento-nanami', 'published'),
  ('huahua', '花花', 'max', 'V2', array['animated', 'cute', 'soft']::text[], '/pet-gallery/huahua.webp', 'https://codex-pets.net/#/pets/huahua', 'published'),
  ('cute-huahua', '萌版花花', 'max', 'V2', array['cute', 'animated', 'soft']::text[], '/pet-gallery/cute-huahua.webp', 'https://codex-pets.net/#/pets/cute-huahua', 'published'),
  ('openai', 'OpenAI', 'Ayrcs', 'V2', '{}'::text[], '/pet-gallery/openai.webp', 'https://codex-pets.net/#/pets/openai', 'published'),
  ('codex-ninja', 'Codex Ninja', 'Szig83', 'V2', array['cute', 'animated']::text[], '/pet-gallery/codex-ninja.webp', 'https://codex-pets.net/#/pets/codex-ninja', 'published'),
  ('higepiyo-anime-v2', 'Higepiyo', 'rintintinjr', 'V2', array['celeb', 'anime', 'chaotic', 'mascot']::text[], '/pet-gallery/higepiyo-anime-v2.webp', 'https://codex-pets.net/#/pets/higepiyo-anime-v2', 'published'),
  ('erza-hibiscus', '艾露莎', 'Lawliet', 'V2', array['animated', 'anime']::text[], '/pet-gallery/erza-hibiscus.webp', 'https://codex-pets.net/#/pets/erza-hibiscus', 'published'),
  ('gandalf-the-white', 'Gandalf the White', 'icaro', 'V2', '{}'::text[], '/pet-gallery/gandalf-the-white.webp', 'https://codex-pets.net/#/pets/gandalf-the-white', 'published'),
  ('fennec-fox', 'Fennec Fox', 'doyeonkp', 'V2', array['cute', 'soft']::text[], '/pet-gallery/fennec-fox.webp', 'https://codex-pets.net/#/pets/fennec-fox', 'published'),
  ('justaway', 'Justaway', 'Justaway', 'V2', array['animated', 'anime', 'cute']::text[], '/pet-gallery/justaway.webp', 'https://codex-pets.net/#/pets/justaway', 'published'),
  ('tortie', 'Tortie', 'yeikel', 'V2', array['cute', 'animated', 'mascot']::text[], '/pet-gallery/tortie.webp', 'https://codex-pets.net/#/pets/tortie', 'published'),
  ('kiki-ragdoll', 'Kiki the Ragdoll Cat', 'kiki', 'V2', array['celeb', 'cute', 'mascot', 'soft', 'pixel']::text[], '/pet-gallery/kiki-ragdoll.webp', 'https://codex-pets.net/#/pets/kiki-ragdoll', 'published'),
  ('landou', 'coco', 'yuki', 'V2', array['cute']::text[], '/pet-gallery/landou.webp', 'https://codex-pets.net/#/pets/landou', 'published'),
  ('xiaoman', 'Xiaoman', 'sapphire', 'V2', '{}'::text[], '/pet-gallery/xiaoman.webp', 'https://codex-pets.net/#/pets/xiaoman', 'published'),
  ('yoshi3d', '요시 - yoshi', 'doyeonkp', 'V2', array['animated', 'game', 'mascot']::text[], '/pet-gallery/yoshi3d.webp', 'https://codex-pets.net/#/pets/yoshi3d', 'published'),
  ('curry-dog', '咖喱狗', 'YuuDan', 'V2', array['celeb', 'cute', 'animated']::text[], '/pet-gallery/curry-dog.webp', 'https://codex-pets.net/#/pets/curry-dog', 'published'),
  ('canal-vorfeed', '凯娜儿·沃菲德', 'HadesTop', 'V2', array['anime', 'robot', 'cute']::text[], '/pet-gallery/canal-vorfeed.webp', 'https://codex-pets.net/#/pets/canal-vorfeed', 'published'),
  ('gandalf-the-grey', 'Gandalf', 'icaro', 'V2', '{}'::text[], '/pet-gallery/gandalf-the-grey.webp', 'https://codex-pets.net/#/pets/gandalf-the-grey', 'published'),
  ('amagai-ruka', 'Amagai Ruka', 'coke', 'V2', array['animated', 'cute', 'anime']::text[], '/pet-gallery/amagai-ruka.webp', 'https://codex-pets.net/#/pets/amagai-ruka', 'published'),
  ('xiaren', '虾仁', 'changyaowu', 'V2', '{}'::text[], '/pet-gallery/xiaren.webp', 'https://codex-pets.net/#/pets/xiaren', 'published'),
  ('creepy', 'Creepy', 'creeper', 'V2', array['game', 'pixel']::text[], '/pet-gallery/creepy.webp', 'https://codex-pets.net/#/pets/creepy', 'published'),
  ('specter-the-unchained', '归溟幽灵鲨', 'eternalsummer', 'V2', array['anime', 'animated', 'cute', 'game']::text[], '/pet-gallery/specter-the-unchained.webp', 'https://codex-pets.net/#/pets/specter-the-unchained', 'published'),
  ('starwitch', 'Starwitch', 'September', 'V2', array['anime']::text[], '/pet-gallery/starwitch.webp', 'https://codex-pets.net/#/pets/starwitch', 'published'),
  ('feiyue-witch-chibi', 'Q版绯月', 'September', 'V2', array['anime']::text[], '/pet-gallery/feiyue-witch-chibi.webp', 'https://codex-pets.net/#/pets/feiyue-witch-chibi', 'published'),
  ('juanjuan', '卷卷', 'Juanjuan', 'V1', array['cute', 'anime', 'soft', 'pixel', 'person']::text[], '/pet-gallery/juanjuan.webp', 'https://codex-pets.net/#/pets/juanjuan', 'published'),
  ('xiao-gu-ga', '小咕嘎', 'stonewall', 'V2', array['animated', 'cute', 'soft']::text[], '/pet-gallery/xiao-gu-ga.webp', 'https://codex-pets.net/#/pets/xiao-gu-ga', 'published'),
  ('tori-tiger', 'Tori Tiger', 'syouzen', 'V2', '{}'::text[], '/pet-gallery/tori-tiger.webp', 'https://codex-pets.net/#/pets/tori-tiger', 'published'),
  ('piccolo-z-feng', '比克', 'snailFeng', 'V2', '{}'::text[], '/pet-gallery/piccolo-z-feng.webp', 'https://codex-pets.net/#/pets/piccolo-z-feng', 'published'),
  ('yintuan', '银团', 'nidehuakucha', 'V2', array['cute', 'animated']::text[], '/pet-gallery/yintuan.webp', 'https://codex-pets.net/#/pets/yintuan', 'published')
on conflict (slug) do update set
  name = excluded.name,
  author = excluded.author,
  format = excluded.format,
  tags = excluded.tags,
  image_path = excluded.image_path,
  source_url = excluded.source_url,
  status = excluded.status,
  updated_at = now();

